### ISSUE TITLE
Non-Obvious Error happening while trying to create JWE token.

### ISSUE THREAD

**Issue by lelabo-marc** [appsup-dart/jose#26]
```dart
  var jwk = JsonWebKey.fromJson({
    'kty': 'oct',
    'k': base64Urlencode('asecret256bitkeyplop12345678plip')
  });
  var builder = JsonWebEncryptionBuilder();
  builder.stringContent = '{"aud": "somekey", "sub": 12, "iss": "auth.example.com", "exp": 1617349353}';
  builder.setProtectedHeader('createdAt', DateTime.now().toIso8601String());
  builder.addRecipient(jwk, algorithm: 'dir');
  builder.encryptionAlgorithm = 'A256GCM';

  var jwe = builder.build();
  print('jwe compact serialization: ${jwe.toCompactSerialization()}');
  print('jwe json serialization: ${jwe.toJson()}');
```

Execption:
```
Unhandled exception:
Null check operator used on a null value
#0      JsonWebKey.encrypt (package:jose/src/jwk.dart:285:69)
#1      JsonWebEncryptionBuilder.build (package:jose/src/jwe.dart:239:30)
#2      main (file:///PROJECT_PATH/bin/dart_client.dart:57:21)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by lelabo-marc** [comment]
Found the source of the exception:

`algorithm` from JsonWebKey class is null while calling encrypt().

This is not obvious from the examples shown but it can simply be resolved... just change the following:
```dart
  var jwk = JsonWebKey.fromJson({
    'kty': 'oct',
    'k': base64Urlencode('asecret256bitkeyplop12345678plip')
  });
```

**Comment by rbellens** [comment]
This should not be throwing. Is fixed now. Will be released soon.
