### ISSUE TITLE
Consider moving to `x509b` package

### ISSUE THREAD

**Issue by cbatson** [appsup-dart/jose#47]
The [x509 package](https://pub.dev/packages/x509) in use -- which hasn't had an update in 20 months -- does not tolerate unrecognized object IDs in certificate extensions. Notably, it will fail when used with Apple intermediate certificates, which have a custom "marker" object ID in the extensions.

<details>
  <summary>Repro code</summary>
  
```dart
import 'package:jose/jose.dart';

void main() {
	// Source: https://www.apple.com/certificateauthority/AppleWWDRCAG6.cer
	JsonWebKey.fromPem('''
-----BEGIN CERTIFICATE-----
MIIDFjCCApygAwIBAgIUIsGhRwp0c2nvU4YSycafPTjzbNcwCgYIKoZIzj0EAwMw
ZzEbMBkGA1UEAwwSQXBwbGUgUm9vdCBDQSAtIEczMSYwJAYDVQQLDB1BcHBsZSBD
ZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkG
A1UEBhMCVVMwHhcNMjEwMzE3MjAzNzEwWhcNMzYwMzE5MDAwMDAwWjB1MUQwQgYD
VQQDDDtBcHBsZSBXb3JsZHdpZGUgRGV2ZWxvcGVyIFJlbGF0aW9ucyBDZXJ0aWZp
Y2F0aW9uIEF1dGhvcml0eTELMAkGA1UECwwCRzYxEzARBgNVBAoMCkFwcGxlIElu
Yy4xCzAJBgNVBAYTAlVTMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEbsQKC94PrlWm
ZXnXgtxzdVJL8T0SGYngDRGpngn3N6PT8JMEb7FDi4bBmPhCnZ3/sq6PF/cGcKXW
sL5vOteRhyJ45x3ASP7cOB+aao90fcpxSv/EZFbniAbNgZGhIhpIo4H6MIH3MBIG
A1UdEwEB/wQIMAYBAf8CAQAwHwYDVR0jBBgwFoAUu7DeoVgziJqkipnevr3rr9rL
JKswRgYIKwYBBQUHAQEEOjA4MDYGCCsGAQUFBzABhipodHRwOi8vb2NzcC5hcHBs
ZS5jb20vb2NzcDAzLWFwcGxlcm9vdGNhZzMwNwYDVR0fBDAwLjAsoCqgKIYmaHR0
cDovL2NybC5hcHBsZS5jb20vYXBwbGVyb290Y2FnMy5jcmwwHQYDVR0OBBYEFD8v
lCNR01DJmig97bB85c+lkGKZMA4GA1UdDwEB/wQEAwIBBjAQBgoqhkiG92NkBgIB
BAIFADAKBggqhkjOPQQDAwNoADBlAjBAXhSq5IyKogMCPtw490BaB677CaEGJXuf
QB/EqZGd6CSjiCtOnuMTbXVXmxxcxfkCMQDTSPxarZXvNrkxU3TkUMI33yzvFVVR
T4wxWJC994OsdcZ4+RGNsYDyR5gmdr0nDGg=
-----END CERTIFICATE-----
''');
}
```
</details>

<details>
  <summary>Error output</summary>
  
```
Unhandled exception:
Bad state: Unable to get name of ObjectIdentifier with nodes [1, 2, 840, 113635, 100, 6, 2, 1]
#0      ObjectIdentifier.name (package:x509/src/objectidentifier.dart:68:7)
#1      ObjectIdentifier.toString (package:x509/src/objectidentifier.dart:74:26)
#2      _StringBase._interpolate (dart:core-patch/string_patch.dart:853:19)
#3      new ExtensionValue.fromAsn1 (package:x509/src/extension.dart:105:60)
#4      new Extension.fromAsn1 (package:x509/src/extension.dart:46:35)
#5      new TbsCertificate.fromAsn1.<anonymous closure> (package:x509/src/certificate.dart:156:39)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#8      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#9      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#10     new List.of (dart:core-patch/array_patch.dart:51:28)
#11     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#12     new TbsCertificate.fromAsn1 (package:x509/src/certificate.dart:157:18)
#13     new X509Certificate.fromAsn1 (package:x509/src/certificate.dart:37:24)
#14     _parseDer (package:x509/src/x509_base.dart:238:30)
#15     parsePem (package:x509/src/x509_base.dart:273:11)
#16     _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:710:21)
#17     Iterable.first (dart:core/iterable.dart:623:13)
#18     new JsonWebKey.fromPem (package:jose/src/jwk.dart:176:32)
#19     main (file:///Users/chuck/projects/flutter/bug5/bin/bug5.dart:4:13)
#20     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
</details>

However, the [x509b package](https://pub.dev/packages/x509b) appears to be tolerant of these certs (due to [this](https://github.com/jeroentrappers/x509/blob/3d5f44df5d26de668851a486d21c8e7f2aea2fbe/lib/src/extension.dart#L113)).

Thank you.

**Comment by rbellens** [comment]
Hi @cbatson ,
Thanks for your suggestion. I don't intend to move to another package. I also manage the `x509` package. I know, I have neglected it a bit, but I've now released a new version and am working on some larger updates. Feel free to report issues in this package.
